GET http://localhost:8080/issues
Accept: application/json
X-Forwarded-Host: gateway.example.com
X-Forwarded-Port: 3000

###

GET http://localhost:8080/api/v2/issues/039a486b-39df-496f-a32d-302cdb39fab7
Accept: application/json

###

GET http://localhost:8080/api/v2/issues/039a486b-39df-496f-a32d-3025db39fab7
Accept: application/json

###
